// flow-typed signature: c04389905fcc974cd62b82041e430c82
// flow-typed version: <<STUB>>/react-native-ui-kitten_v^4.0.1/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-ui-kitten'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-ui-kitten' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-ui-kitten/theme/application/applicationProvider.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/index' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/mapping/mappingContext' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/mapping/mappingProvider.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/modal/modal.service' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/modal/modalPanel.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/style/style.service' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/style/styleConsumer.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/style/styleConsumer.service' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/style/styleProvider.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/style/type' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/support/tests/index' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/theme/theme.service' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/theme/themeConsumer.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/theme/themeContext' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/theme/themeProvider.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/theme/theme/type' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/avatar/avatar.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/bottomNavigation/bottomNavigation.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/bottomNavigation/bottomNavigationTab.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/button/button.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/buttonGroup/buttonGroup.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/checkbox/checkbox.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/index' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/input/input.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/layout/layout.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/list/list.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/list/listItem.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/modal/modal.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/overflowMenu/overflowMenu.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/overflowMenu/overflowMenuItem.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/popover/measure.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/popover/popover.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/popover/popoverView.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/popover/type' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/radio/radio.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/radioGroup/radioGroup.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/components/arrow/arrow.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/components/checkmark/checkmark.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/components/index' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/components/tabIndicator/tabIndicator.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/services/index' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/services/props.service' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/services/validation.service' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/tests/index' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/typings/index' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/typings/props' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/support/typings/type' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/tab/tab.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/tab/tabBar.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/tab/tabView.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/text/text.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/toggle/toggle.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/tooltip/tooltip.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/topNavigation/topNavigation.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/topNavigation/topNavigationAction.component' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/ui/viewPager/viewPager.component' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-ui-kitten/index' {
  declare module.exports: $Exports<'react-native-ui-kitten'>;
}
declare module 'react-native-ui-kitten/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten'>;
}
declare module 'react-native-ui-kitten/theme/application/applicationProvider.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/application/applicationProvider.component'>;
}
declare module 'react-native-ui-kitten/theme/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/index'>;
}
declare module 'react-native-ui-kitten/theme/mapping/mappingContext.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/mapping/mappingContext'>;
}
declare module 'react-native-ui-kitten/theme/mapping/mappingProvider.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/mapping/mappingProvider.component'>;
}
declare module 'react-native-ui-kitten/theme/modal/modal.service.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/modal/modal.service'>;
}
declare module 'react-native-ui-kitten/theme/modal/modalPanel.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/modal/modalPanel.component'>;
}
declare module 'react-native-ui-kitten/theme/style/style.service.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/style/style.service'>;
}
declare module 'react-native-ui-kitten/theme/style/styleConsumer.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/style/styleConsumer.component'>;
}
declare module 'react-native-ui-kitten/theme/style/styleConsumer.service.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/style/styleConsumer.service'>;
}
declare module 'react-native-ui-kitten/theme/style/styleProvider.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/style/styleProvider.component'>;
}
declare module 'react-native-ui-kitten/theme/style/type.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/style/type'>;
}
declare module 'react-native-ui-kitten/theme/support/tests/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/support/tests/index'>;
}
declare module 'react-native-ui-kitten/theme/theme/theme.service.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/theme/theme.service'>;
}
declare module 'react-native-ui-kitten/theme/theme/themeConsumer.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/theme/themeConsumer.component'>;
}
declare module 'react-native-ui-kitten/theme/theme/themeContext.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/theme/themeContext'>;
}
declare module 'react-native-ui-kitten/theme/theme/themeProvider.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/theme/themeProvider.component'>;
}
declare module 'react-native-ui-kitten/theme/theme/type.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/theme/theme/type'>;
}
declare module 'react-native-ui-kitten/ui/avatar/avatar.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/avatar/avatar.component'>;
}
declare module 'react-native-ui-kitten/ui/bottomNavigation/bottomNavigation.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/bottomNavigation/bottomNavigation.component'>;
}
declare module 'react-native-ui-kitten/ui/bottomNavigation/bottomNavigationTab.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/bottomNavigation/bottomNavigationTab.component'>;
}
declare module 'react-native-ui-kitten/ui/button/button.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/button/button.component'>;
}
declare module 'react-native-ui-kitten/ui/buttonGroup/buttonGroup.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/buttonGroup/buttonGroup.component'>;
}
declare module 'react-native-ui-kitten/ui/checkbox/checkbox.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/checkbox/checkbox.component'>;
}
declare module 'react-native-ui-kitten/ui/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/index'>;
}
declare module 'react-native-ui-kitten/ui/input/input.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/input/input.component'>;
}
declare module 'react-native-ui-kitten/ui/layout/layout.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/layout/layout.component'>;
}
declare module 'react-native-ui-kitten/ui/list/list.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/list/list.component'>;
}
declare module 'react-native-ui-kitten/ui/list/listItem.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/list/listItem.component'>;
}
declare module 'react-native-ui-kitten/ui/modal/modal.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/modal/modal.component'>;
}
declare module 'react-native-ui-kitten/ui/overflowMenu/overflowMenu.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/overflowMenu/overflowMenu.component'>;
}
declare module 'react-native-ui-kitten/ui/overflowMenu/overflowMenuItem.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/overflowMenu/overflowMenuItem.component'>;
}
declare module 'react-native-ui-kitten/ui/popover/measure.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/popover/measure.component'>;
}
declare module 'react-native-ui-kitten/ui/popover/popover.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/popover/popover.component'>;
}
declare module 'react-native-ui-kitten/ui/popover/popoverView.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/popover/popoverView.component'>;
}
declare module 'react-native-ui-kitten/ui/popover/type.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/popover/type'>;
}
declare module 'react-native-ui-kitten/ui/radio/radio.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/radio/radio.component'>;
}
declare module 'react-native-ui-kitten/ui/radioGroup/radioGroup.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/radioGroup/radioGroup.component'>;
}
declare module 'react-native-ui-kitten/ui/support/components/arrow/arrow.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/components/arrow/arrow.component'>;
}
declare module 'react-native-ui-kitten/ui/support/components/checkmark/checkmark.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/components/checkmark/checkmark.component'>;
}
declare module 'react-native-ui-kitten/ui/support/components/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/components/index'>;
}
declare module 'react-native-ui-kitten/ui/support/components/tabIndicator/tabIndicator.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/components/tabIndicator/tabIndicator.component'>;
}
declare module 'react-native-ui-kitten/ui/support/services/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/services/index'>;
}
declare module 'react-native-ui-kitten/ui/support/services/props.service.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/services/props.service'>;
}
declare module 'react-native-ui-kitten/ui/support/services/validation.service.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/services/validation.service'>;
}
declare module 'react-native-ui-kitten/ui/support/tests/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/tests/index'>;
}
declare module 'react-native-ui-kitten/ui/support/typings/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/typings/index'>;
}
declare module 'react-native-ui-kitten/ui/support/typings/props.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/typings/props'>;
}
declare module 'react-native-ui-kitten/ui/support/typings/type.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/support/typings/type'>;
}
declare module 'react-native-ui-kitten/ui/tab/tab.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/tab/tab.component'>;
}
declare module 'react-native-ui-kitten/ui/tab/tabBar.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/tab/tabBar.component'>;
}
declare module 'react-native-ui-kitten/ui/tab/tabView.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/tab/tabView.component'>;
}
declare module 'react-native-ui-kitten/ui/text/text.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/text/text.component'>;
}
declare module 'react-native-ui-kitten/ui/toggle/toggle.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/toggle/toggle.component'>;
}
declare module 'react-native-ui-kitten/ui/tooltip/tooltip.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/tooltip/tooltip.component'>;
}
declare module 'react-native-ui-kitten/ui/topNavigation/topNavigation.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/topNavigation/topNavigation.component'>;
}
declare module 'react-native-ui-kitten/ui/topNavigation/topNavigationAction.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/topNavigation/topNavigationAction.component'>;
}
declare module 'react-native-ui-kitten/ui/viewPager/viewPager.component.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/ui/viewPager/viewPager.component'>;
}
