const PREFIX = "@@remedy/";

export const REMEDY_INIT = `${PREFIX}AUTH_INIT`;
export const HANDLE_FAILURE = `${PREFIX}HANDLE_FAILURE`;
export const REMEDY_GET_SUCCESS = `${PREFIX}REMEDY_GET_SUCCESS`;
export const GET_RESEARCH_SUCCESS = `${PREFIX}GET_RESEARCH_SUCCESS`;
export const RESET_RESEARCH = `${PREFIX}RESET_RESEARCH`;

export const RESET_NOTIFICATION = `${PREFIX}RESET_NOTIFICATION`;
