const PREFIX = "@@verification/";

export const VERIFICATION_INIT = `${PREFIX}VERIFICATION_INIT`;
export const HANDLE_FAILURE = `${PREFIX}HANDLE_FAILURE`;
export const GET_VERIFICATION_LIST_SUCCESS = `${PREFIX}GET_VERIFICATION_LIST_SUCCESS`;
export const GET_VERIFICATION_SUCCESS = `${PREFIX}GET_VERIFICATION_SUCCESS`;
export const RESET_VERIFICATION = `${PREFIX}RESET_VERIFICATION`;
export const VERIFICATION_SUCCESS = `${PREFIX}VERIFICATION_SUCCESS`;
export const INITIALIZE_VERIFICATION = `${PREFIX}INITIALIZE_VERIFICATION`;
export const INITIALIZE_VERIFICATIONS = `${PREFIX}INITIALIZE_VERIFICATIONS`;

export const RESET_NOTIFICATION = `${PREFIX}RESET_NOTIFICATION`;
