// flow-typed signature: adcd95dc0dcbbb54b4e0e2db7fdce413
// flow-typed version: <<STUB>>/@eva-design/eva_v^1.0.0/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@eva-design/eva'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@eva-design/eva' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@eva-design/eva/index' {
  declare module.exports: $Exports<'@eva-design/eva'>;
}
declare module '@eva-design/eva/index.js' {
  declare module.exports: $Exports<'@eva-design/eva'>;
}
